### ISSUE TITLE
bug - ImportError: libQt6Widgets.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gregLibert** [massalabs/Thyra-Menu-Bar-App#37]
**Describe the bug**
When I run the thyra-app after installation on linux, i have the following error:

```shell
$ ~/thyra-app 
Traceback (most recent call last):
  File "thyra_app.py", line 10, in <module>
ImportError: libQt6Widgets.so.6: cannot open shared object file: No such file or directory
[8442] Failed to execute script 'thyra_app' due to unhandled exception!
```

**Comment by gregLibert** [comment]
After installing libqt6widgets6 (`sudo apt install libqt6widgets6`), I have the following error:
```shell
$ ~/thyra-app                   
Traceback (most recent call last):
  File "thyra_app.py", line 10, in <module>
ImportError: /lib/x86_64-linux-gnu/libQt6Widgets.so.6: undefined symbol: qt_is_gui_used, version Qt_6
[8966] Failed to execute script 'thyra_app' due to unhandled exception!
```

**Comment by gregLibert** [comment]
This problem doesn't exist when I build manually the application.
