### ISSUE TITLE
bug - ModuleNotFoundError: No module named 'psutil'

### ISSUE THREAD

**Issue by gregLibert** [massalabs/Thyra-Menu-Bar-App#38]
**Describe the bug**
Launching this project after cloning and installing the dependencies on linux returns the following error:

```shell
python3 thyra_app.py   
Traceback (most recent call last):
  File "/home/greg/code/Thyra-Menu-Bar-App/thyra_app.py", line 12, in <module>
    from utils.background_thyra_scripts import Thyra
  File "/home/greg/code/Thyra-Menu-Bar-App/utils/background_thyra_scripts.py", line 6, in <module>
    import utils.background_process
  File "/home/greg/code/Thyra-Menu-Bar-App/utils/background_process.py", line 7, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**To Reproduce**
On linux,

1. git clone git@github.com:massalabs/Thyra-Menu-Bar-App.git
2. cd Thyra-Menu-Bar-App
3. pip3 install PySide6
4. python3 thyra_app.py
5. See error

**Comment by gregLibert** [comment]
Installing psutil (` pip3 install psutil`) solved this issue.
